from pathlib import Path
p=Path('app/src/main/java/com/example/workhours/WagePanel.java')
s=p.read_text()
s=s.replace('import android.app.Activity;\n','import android.app.Activity;\nimport android.app.AlertDialog;\n',1)
s=s.replace('import android.widget.LinearLayout;\n','import android.widget.LinearLayout;\nimport android.widget.NumberPicker;\n',1)
s=s.replace('''        monthTitle = text("", 18, true);\n        monthTitle.setGravity(Gravity.CENTER);\n        monthNav.addView(monthTitle, new LinearLayout.LayoutParams(0, -2, 1f));''','''        monthTitle = text("", 18, true);\n        monthTitle.setGravity(Gravity.CENTER);\n        monthTitle.setPadding(dp(8), dp(12), dp(8), dp(12));\n        monthTitle.setOnClickListener(v -> chooseMonth());\n        monthNav.addView(monthTitle, new LinearLayout.LayoutParams(0, -2, 1f));''',1)
anchor='''    private void chooseRangeDate(boolean startDate) {\n'''
method='''    private void chooseMonth() {\n        LocalDate ws = getWorkStartDate();\n        int minYear = ws == null ? Math.max(2000, displayedMonth.getYear() - 20) : ws.getYear();\n        int maxYear = YearMonth.now().getYear();\n\n        LinearLayout box = horizontal();\n        box.setPadding(dp(24), dp(12), dp(24), dp(4));\n        box.setGravity(Gravity.CENTER);\n\n        NumberPicker yearPicker = new NumberPicker(host);\n        yearPicker.setMinValue(minYear);\n        yearPicker.setMaxValue(maxYear);\n        yearPicker.setValue(Math.max(minYear, Math.min(maxYear, displayedMonth.getYear())));\n        box.addView(yearPicker, new LinearLayout.LayoutParams(0, -2, 1f));\n\n        NumberPicker monthPicker = new NumberPicker(host);\n        monthPicker.setMinValue(1);\n        monthPicker.setMaxValue(12);\n        monthPicker.setDisplayedValues(new String[]{"1月","2月","3月","4月","5月","6月","7月","8月","9月","10月","11月","12月"});\n        monthPicker.setValue(displayedMonth.getMonthValue());\n        box.addView(monthPicker, new LinearLayout.LayoutParams(0, -2, 1f));\n\n        AlertDialog dialog = new AlertDialog.Builder(host)\n                .setTitle("选择月份")\n                .setView(box)\n                .setNegativeButton("取消", null)\n                .setPositiveButton("确定", null)\n                .create();\n        dialog.setOnShowListener(x -> dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v -> {\n            YearMonth picked = YearMonth.of(yearPicker.getValue(), monthPicker.getValue());\n            YearMonth now = YearMonth.now();\n            YearMonth first = ws == null ? null : YearMonth.from(ws);\n            if (picked.isAfter(now)) {\n                Toast.makeText(host, "不能选择未来月份", Toast.LENGTH_SHORT).show();\n                return;\n            }\n            if (first != null && picked.isBefore(first)) {\n                Toast.makeText(host, "不能早于工作开始月份", Toast.LENGTH_SHORT).show();\n                return;\n            }\n            displayedMonth = picked;\n            refreshMonth();\n            dialog.dismiss();\n        }));\n        dialog.show();\n    }\n\n'''
if anchor not in s: raise SystemExit('anchor not found')
s=s.replace(anchor,method+anchor,1)
s=s.replace('''        monthTitle.setText(displayedMonth.getYear() + "年" + displayedMonth.getMonthValue() + "月");''','''        monthTitle.setText(displayedMonth.getYear() + "年" + displayedMonth.getMonthValue() + "月\\n点击选择月份");''',1)
p.write_text(s)
