from pathlib import Path

# Patch WagePanel: expose month wage summary and hide/remove month subtab usage.
p=Path('app/src/main/java/com/example/workhours/WagePanel.java')
s=p.read_text()
# Public API for shared month summary.
anchor='''    public void refresh() {\n        if (monthSummary != null) refreshAll();\n    }\n'''
method='''    public void refresh() {\n        if (monthSummary != null) refreshAll();\n    }\n\n    public void setDisplayedMonth(YearMonth month) {\n        if (month == null) return;\n        displayedMonth = month;\n        refreshMonth();\n    }\n\n    public float getDisplayedMonthWage() {\n        YearMonth month = displayedMonth;\n        LocalDate ws = getWorkStartDate();\n        LocalDate start = month.atDay(1);\n        if (ws != null && start.isBefore(ws)) start = ws;\n        LocalDate end = month.equals(YearMonth.now()) ? LocalDate.now() : month.atEndOfMonth();\n        if (start.isAfter(end)) return 0f;\n        float wage = 0f;\n        for (LocalDate d = start; !d.isAfter(end); d = d.plusDays(1)) wage += getWageForDate(d);\n        return wage;\n    }\n'''
if anchor not in s: raise SystemExit('wage public anchor missing')
s=s.replace(anchor,method,1)
# Change wage subtabs from 3 to 2, remove month tab button from UI and show function.
s=s.replace('''        weekTabButton = button("星期");\n        dayTabButton = button("日期");\n        monthTabButton = button("月份");\n        viewTabs.addView(weekTabButton, new LinearLayout.LayoutParams(0, dp(46), 1f));\n        LinearLayout.LayoutParams middleTabParams = new LinearLayout.LayoutParams(0, dp(46), 1f);\n        middleTabParams.leftMargin = dp(6);\n        viewTabs.addView(dayTabButton, middleTabParams);\n        LinearLayout.LayoutParams lastTabParams = new LinearLayout.LayoutParams(0, dp(46), 1f);\n        lastTabParams.leftMargin = dp(6);\n        viewTabs.addView(monthTabButton, lastTabParams);''','''        weekTabButton = button("星期");\n        dayTabButton = button("日期");\n        viewTabs.addView(weekTabButton, new LinearLayout.LayoutParams(0, dp(46), 1f));\n        LinearLayout.LayoutParams middleTabParams = new LinearLayout.LayoutParams(0, dp(46), 1f);\n        middleTabParams.leftMargin = dp(6);\n        viewTabs.addView(dayTabButton, middleTabParams);''',1)
s=s.replace('''        monthContent = vertical();\n        root.addView(weekContent);\n        root.addView(dayContent);\n        root.addView(monthContent);''','''        monthContent = vertical();\n        root.addView(weekContent);\n        root.addView(dayContent);''',1)
# Remove month section UI block by slicing.
start=s.find('        TextView monthSection = text("按月查看工资"')
end=s.find('        weekTabButton.setOnClickListener', start)
if start!=-1 and end!=-1:
    s=s[:start]+s[end:]
s=s.replace('''        weekTabButton.setOnClickListener(v -> showViewTab(0));\n        dayTabButton.setOnClickListener(v -> showViewTab(1));\n        monthTabButton.setOnClickListener(v -> showViewTab(2));\n        showViewTab(0);''','''        weekTabButton.setOnClickListener(v -> showViewTab(0));\n        dayTabButton.setOnClickListener(v -> showViewTab(1));\n        showViewTab(0);''',1)
# Keep hidden month logic for shared summary; adjust showViewTab.
s=s.replace('''        monthContent.setVisibility(tab == 2 ? View.VISIBLE : View.GONE);\n        UiStyle.button(host, weekTabButton, tab == 0);\n        UiStyle.button(host, dayTabButton, tab == 1);\n        UiStyle.button(host, monthTabButton, tab == 2);\n        weekTabButton.setEnabled(tab != 0);\n        dayTabButton.setEnabled(tab != 1);\n        monthTabButton.setEnabled(tab != 2);\n        if (tab == 0) refreshWeek();\n        else if (tab == 1) refreshDay();\n        else refreshMonth();''','''        UiStyle.button(host, weekTabButton, tab == 0);\n        UiStyle.button(host, dayTabButton, tab == 1);\n        weekTabButton.setEnabled(tab != 0);\n        dayTabButton.setEnabled(tab != 1);\n        if (tab == 0) refreshWeek();\n        else refreshDay();''',1)
# refresh() cannot depend on monthSummary now.
s=s.replace('''    public void refresh() {\n        if (monthSummary != null) refreshAll();\n    }''','''    public void refresh() {\n        refreshAll();\n    }''',1)
p.write_text(s)

# Patch MainActivity: shared month summary above work/wage tabs, work detail tabs only week/date.
p=Path('app/src/main/java/com/example/workhours/MainActivity.java')
s=p.read_text()
s=s.replace('''    private TextView monthTitle, totalHoursText, statusStatsText;''','''    private TextView monthTitle, totalHoursText, totalWageText, statusStatsText;''',1)
s=s.replace('''    private Button workWeekTabButton, workDateTabButton, workMonthTabButton;''','''    private Button workWeekTabButton, workDateTabButton;''',1)
# Insert shared summary after top bar, before quick switch.
anchor='''        top.addView(settings, new LinearLayout.LayoutParams(dp(86), dp(48)));\n\n        LinearLayout quickSwitch = horizontal();'''
insert='''        top.addView(settings, new LinearLayout.LayoutParams(dp(86), dp(48)));\n\n        buildSharedMonthSummary(root);\n\n        LinearLayout quickSwitch = horizontal();'''
if anchor not in s: raise SystemExit('main shared anchor missing')
s=s.replace(anchor,insert,1)
# Replace work tabs and month container layout.
old='''        LinearLayout workViewTabs = horizontal();\n        LinearLayout.LayoutParams workViewTabsParams = new LinearLayout.LayoutParams(-1, dp(46));\n        workViewTabsParams.topMargin = dp(18);\n        workContent.addView(workViewTabs, workViewTabsParams);\n        workWeekTabButton = button("星期");\n        workDateTabButton = button("日期");\n        workMonthTabButton = button("月份");\n        workViewTabs.addView(workWeekTabButton, new LinearLayout.LayoutParams(0, dp(46), 1f));\n        LinearLayout.LayoutParams workDateTabParams = new LinearLayout.LayoutParams(0, dp(46), 1f);\n        workDateTabParams.leftMargin = dp(6);\n        workViewTabs.addView(workDateTabButton, workDateTabParams);\n        LinearLayout.LayoutParams workMonthTabParams = new LinearLayout.LayoutParams(0, dp(46), 1f);\n        workMonthTabParams.leftMargin = dp(6);\n        workViewTabs.addView(workMonthTabButton, workMonthTabParams);\n\n        weekSectionContainer = vertical();\n        rangeSectionContainer = vertical();\n        monthSectionContainer = vertical();\n        workContent.addView(weekSectionContainer);\n        workContent.addView(rangeSectionContainer);\n        workContent.addView(monthSectionContainer);\n\n        buildWeekSection(weekSectionContainer);\n        buildRangeSection(rangeSectionContainer);\n        buildMonthSection(monthSectionContainer);\n        TextView ex = text("本月异常记录", 19, true);\n        ex.setPadding(0, dp(24), 0, dp(8));\n        monthSectionContainer.addView(ex);\n        exceptionsContainer = vertical();\n        monthSectionContainer.addView(exceptionsContainer);\n\n        workWeekTabButton.setOnClickListener(v -> showWorkViewTab(0));\n        workDateTabButton.setOnClickListener(v -> showWorkViewTab(1));\n        workMonthTabButton.setOnClickListener(v -> showWorkViewTab(2));\n        showWorkViewTab(2);'''
new='''        LinearLayout workViewTabs = horizontal();\n        LinearLayout.LayoutParams workViewTabsParams = new LinearLayout.LayoutParams(-1, dp(46));\n        workViewTabsParams.topMargin = dp(18);\n        workContent.addView(workViewTabs, workViewTabsParams);\n        workWeekTabButton = button("星期");\n        workDateTabButton = button("日期");\n        workViewTabs.addView(workWeekTabButton, new LinearLayout.LayoutParams(0, dp(46), 1f));\n        LinearLayout.LayoutParams workDateTabParams = new LinearLayout.LayoutParams(0, dp(46), 1f);\n        workDateTabParams.leftMargin = dp(6);\n        workViewTabs.addView(workDateTabButton, workDateTabParams);\n\n        weekSectionContainer = vertical();\n        rangeSectionContainer = vertical();\n        workContent.addView(weekSectionContainer);\n        workContent.addView(rangeSectionContainer);\n        buildWeekSection(weekSectionContainer);\n        buildRangeSection(rangeSectionContainer);\n\n        workWeekTabButton.setOnClickListener(v -> showWorkViewTab(0));\n        workDateTabButton.setOnClickListener(v -> showWorkViewTab(1));\n        showWorkViewTab(0);'''
if old not in s: raise SystemExit('main work tabs block missing')
s=s.replace(old,new,1)
# Replace showWorkViewTab.
start=s.index('    private void showWorkViewTab(int tab) {')
end=s.index('    private void showStatsTab(boolean wage)',start)
new_method='''    private void showWorkViewTab(int tab) {\n        if (weekSectionContainer == null || rangeSectionContainer == null) return;\n        weekSectionContainer.setVisibility(tab == 0 ? View.VISIBLE : View.GONE);\n        rangeSectionContainer.setVisibility(tab == 1 ? View.VISIBLE : View.GONE);\n        UiStyle.button(this, workWeekTabButton, tab == 0);\n        UiStyle.button(this, workDateTabButton, tab == 1);\n        workWeekTabButton.setEnabled(tab != 0);\n        workDateTabButton.setEnabled(tab != 1);\n        if (tab == 0) refreshWeek(); else calculateRange();\n    }\n\n'''
s=s[:start]+new_method+s[end:]
# Replace buildMonthSection with shared compact summary that includes calendar removed.
start=s.index('    private void buildMonthSection(LinearLayout root) {')
end=s.index('    private void buildWeekSection(LinearLayout root) {', start)
shared='''    private void buildSharedMonthSummary(LinearLayout root) {\n        LinearLayout nav = horizontal();\n        nav.setGravity(Gravity.CENTER_VERTICAL);\n        LinearLayout.LayoutParams np = new LinearLayout.LayoutParams(-1, dp(58));\n        np.topMargin = dp(14);\n        root.addView(nav, np);\n        previousMonthButton = button("‹");\n        previousMonthButton.setTextSize(24);\n        previousMonthButton.setOnClickListener(v -> { YearMonth target=displayedMonth.minusMonths(1); LocalDate ws=getWorkStartDate(); if(ws==null||!target.isBefore(YearMonth.from(ws))){displayedMonth=target;refreshMonth();}});\n        nav.addView(previousMonthButton,new LinearLayout.LayoutParams(dp(58),dp(48)));\n        monthTitle=text("",18,true); monthTitle.setGravity(Gravity.CENTER); monthTitle.setPadding(dp(8),dp(10),dp(8),dp(10)); monthTitle.setOnClickListener(v->chooseWorkMonth());\n        nav.addView(monthTitle,new LinearLayout.LayoutParams(0,-2,1f));\n        nextMonthButton=button("›"); nextMonthButton.setTextSize(24); nextMonthButton.setOnClickListener(v->{if(displayedMonth.isBefore(YearMonth.now())){displayedMonth=displayedMonth.plusMonths(1);refreshMonth();}});\n        nav.addView(nextMonthButton,new LinearLayout.LayoutParams(dp(58),dp(48)));\n\n        LinearLayout cards=horizontal();\n        root.addView(cards,new LinearLayout.LayoutParams(-1,-2));\n        LinearLayout hoursCard=card();\n        hoursCard.addView(text("本月工时",13,false));\n        totalHoursText=text("",25,true); totalHoursText.setPadding(0,dp(4),0,dp(4)); hoursCard.addView(totalHoursText);\n        statusStatsText=statLineText(); statusStatsText.setTextSize(11); statusStatsText.setSingleLine(false); hoursCard.addView(statusStatsText);\n        cards.addView(hoursCard,new LinearLayout.LayoutParams(0,-2,1f));\n        LinearLayout wageCard=card();\n        wageCard.addView(text("本月工资",13,false));\n        totalWageText=text("£0.00",25,true); totalWageText.setPadding(0,dp(4),0,dp(4)); wageCard.addView(totalWageText);\n        TextView wageHint=text("点击工资统计查看明细",11,false); wageCard.addView(wageHint);\n        LinearLayout.LayoutParams wp=new LinearLayout.LayoutParams(0,-2,1f); wp.leftMargin=dp(8); cards.addView(wageCard,wp);\n    }\n\n'''
s=s[:start]+shared+s[end:]
# refreshAll and refreshMonth adapt no calendar/exceptions requirement.
s=s.replace('''    private void refreshAll() { updateRangeButtons(); refreshMonth(); refreshWeek(); calculateRange(); }''','''    private void refreshAll() { updateRangeButtons(); refreshMonth(); refreshWeek(); calculateRange(); }''',1)
start=s.index('    private void refreshMonth() {')
end=s.index('    private void refreshWeek() {',start)
refresh='''    private void refreshMonth() {\n        LocalDate today=LocalDate.now(); YearMonth now=YearMonth.from(today); LocalDate ws=getWorkStartDate(); YearMonth first=ws==null?null:YearMonth.from(ws);\n        if(displayedMonth.isAfter(now))displayedMonth=now; if(first!=null&&displayedMonth.isBefore(first))displayedMonth=first;\n        monthTitle.setText(displayedMonth.getYear()+"年"+displayedMonth.getMonthValue()+"月\\n点击选择月份");\n        previousMonthButton.setEnabled(first==null||displayedMonth.isAfter(first)); nextMonthButton.setEnabled(displayedMonth.isBefore(now));\n        LocalDate start=displayedMonth.atDay(1); if(ws!=null&&start.isBefore(ws))start=ws; LocalDate end=displayedMonth.equals(now)?today:displayedMonth.atEndOfMonth();\n        Stats st=collectStats(start,end); totalHoursText.setText(formatDurationHours(st.totalHours));\n        statusStatsText.setText(StatusStatsFormatter.format(st.workDays,st.leaveDays,st.holidayDays,st.restDays));\n        if(wagePanel!=null){ wagePanel.setDisplayedMonth(displayedMonth); totalWageText.setText(String.format(Locale.UK,"£%.2f",wagePanel.getDisplayedMonthWage())); }\n    }\n\n'''
s=s[:start]+refresh+s[end:]
# onResume guard no calendar anymore.
s=s.replace('''        if (calendarGrid == null) return;''','''        if (monthTitle == null) return;''',1)
# showStatsTab should sync month wage panel.
s=s.replace('''        if (wage && wagePanel != null) wagePanel.refresh();''','''        if (wage && wagePanel != null) { wagePanel.setDisplayedMonth(displayedMonth); wagePanel.refresh(); }''',1)
p.write_text(s)
