from pathlib import Path
p=Path('app/src/main/java/com/example/workhours/MainActivity.java')
s=p.read_text()

s=s.replace('import android.widget.LinearLayout;\n','import android.widget.LinearLayout;\nimport android.widget.NumberPicker;\n',1)

s=s.replace('''    private LinearLayout weekSectionContainer, rangeSectionContainer;\n    private LinearLayout workContent, wageContent;\n''','''    private LinearLayout monthSectionContainer, weekSectionContainer, rangeSectionContainer;\n    private LinearLayout workContent, wageContent;\n    private Button workWeekTabButton, workDateTabButton, workMonthTabButton;\n''',1)

old='''        buildMonthSection(workContent);\n\n        TextView statsTitle = text("更多统计", 19, true);\n        statsTitle.setPadding(0, dp(24), 0, dp(8));\n        workContent.addView(statsTitle);\n        LinearLayout statsButtons = horizontal();\n        workContent.addView(statsButtons);\n        Button weekToggle = button("周统计");\n        Button rangeToggle = button("范围统计");\n        statsButtons.addView(weekToggle, new LinearLayout.LayoutParams(0, dp(48), 1f));\n        LinearLayout.LayoutParams rtp = new LinearLayout.LayoutParams(0, dp(48), 1f); rtp.leftMargin = dp(8);\n        statsButtons.addView(rangeToggle, rtp);\n\n        weekSectionContainer = vertical();\n        weekSectionContainer.setVisibility(View.GONE);\n        workContent.addView(weekSectionContainer);\n        buildWeekSection(weekSectionContainer);\n        rangeSectionContainer = vertical();\n        rangeSectionContainer.setVisibility(View.GONE);\n        workContent.addView(rangeSectionContainer);\n        buildRangeSection(rangeSectionContainer);\n        weekToggle.setOnClickListener(v -> {\n            boolean show = weekSectionContainer.getVisibility() != View.VISIBLE;\n            weekSectionContainer.setVisibility(show ? View.VISIBLE : View.GONE);\n            if (show) rangeSectionContainer.setVisibility(View.GONE);\n        });\n        rangeToggle.setOnClickListener(v -> {\n            boolean show = rangeSectionContainer.getVisibility() != View.VISIBLE;\n            rangeSectionContainer.setVisibility(show ? View.VISIBLE : View.GONE);\n            if (show) weekSectionContainer.setVisibility(View.GONE);\n        });\n\n        TextView ex = text("本月异常记录", 19, true);\n        ex.setPadding(0, dp(24), 0, dp(8));\n        workContent.addView(ex);\n        exceptionsContainer = vertical();\n        workContent.addView(exceptionsContainer);\n'''
new='''        LinearLayout workViewTabs = horizontal();\n        LinearLayout.LayoutParams workViewTabsParams = new LinearLayout.LayoutParams(-1, dp(46));\n        workViewTabsParams.topMargin = dp(18);\n        workContent.addView(workViewTabs, workViewTabsParams);\n        workWeekTabButton = button("星期");\n        workDateTabButton = button("日期");\n        workMonthTabButton = button("月份");\n        workViewTabs.addView(workWeekTabButton, new LinearLayout.LayoutParams(0, dp(46), 1f));\n        LinearLayout.LayoutParams workDateTabParams = new LinearLayout.LayoutParams(0, dp(46), 1f);\n        workDateTabParams.leftMargin = dp(6);\n        workViewTabs.addView(workDateTabButton, workDateTabParams);\n        LinearLayout.LayoutParams workMonthTabParams = new LinearLayout.LayoutParams(0, dp(46), 1f);\n        workMonthTabParams.leftMargin = dp(6);\n        workViewTabs.addView(workMonthTabButton, workMonthTabParams);\n\n        weekSectionContainer = vertical();\n        rangeSectionContainer = vertical();\n        monthSectionContainer = vertical();\n        workContent.addView(weekSectionContainer);\n        workContent.addView(rangeSectionContainer);\n        workContent.addView(monthSectionContainer);\n\n        buildWeekSection(weekSectionContainer);\n        buildRangeSection(rangeSectionContainer);\n        buildMonthSection(monthSectionContainer);\n        TextView ex = text("本月异常记录", 19, true);\n        ex.setPadding(0, dp(24), 0, dp(8));\n        monthSectionContainer.addView(ex);\n        exceptionsContainer = vertical();\n        monthSectionContainer.addView(exceptionsContainer);\n\n        workWeekTabButton.setOnClickListener(v -> showWorkViewTab(0));\n        workDateTabButton.setOnClickListener(v -> showWorkViewTab(1));\n        workMonthTabButton.setOnClickListener(v -> showWorkViewTab(2));\n        showWorkViewTab(2);\n'''
if old not in s:
    raise SystemExit('main layout anchor not found')
s=s.replace(old,new,1)

anchor='''    private void showStatsTab(boolean wage) {\n'''
method='''    private void showWorkViewTab(int tab) {\n        if (weekSectionContainer == null || rangeSectionContainer == null || monthSectionContainer == null) return;\n        weekSectionContainer.setVisibility(tab == 0 ? View.VISIBLE : View.GONE);\n        rangeSectionContainer.setVisibility(tab == 1 ? View.VISIBLE : View.GONE);\n        monthSectionContainer.setVisibility(tab == 2 ? View.VISIBLE : View.GONE);\n        UiStyle.button(this, workWeekTabButton, tab == 0);\n        UiStyle.button(this, workDateTabButton, tab == 1);\n        UiStyle.button(this, workMonthTabButton, tab == 2);\n        workWeekTabButton.setEnabled(tab != 0);\n        workDateTabButton.setEnabled(tab != 1);\n        workMonthTabButton.setEnabled(tab != 2);\n        if (tab == 0) refreshWeek();\n        else if (tab == 1) calculateRange();\n        else refreshMonth();\n    }\n\n'''
if anchor not in s: raise SystemExit('showStatsTab anchor not found')
s=s.replace(anchor,method+anchor,1)

s=s.replace('''        monthTitle = text("", 20, true); monthTitle.setGravity(Gravity.CENTER);\n        nav.addView(monthTitle, new LinearLayout.LayoutParams(0, -2, 1f));''','''        monthTitle = text("", 18, true); monthTitle.setGravity(Gravity.CENTER);\n        monthTitle.setPadding(dp(8), dp(12), dp(8), dp(12));\n        monthTitle.setOnClickListener(v -> chooseWorkMonth());\n        nav.addView(monthTitle, new LinearLayout.LayoutParams(0, -2, 1f));''',1)

s=s.replace('''        weekTitle = text("", 17, true); weekTitle.setGravity(Gravity.CENTER); nav.addView(weekTitle, new LinearLayout.LayoutParams(0, -2, 1f));''','''        weekTitle = text("", 17, true); weekTitle.setGravity(Gravity.CENTER);\n        weekTitle.setPadding(dp(8), dp(12), dp(8), dp(12));\n        weekTitle.setOnClickListener(v -> chooseWorkWeek());\n        nav.addView(weekTitle, new LinearLayout.LayoutParams(0, -2, 1f));''',1)

s=s.replace('''        Button calc = button("统计这段时间"); UiStyle.button(this, calc, true); calc.setOnClickListener(v -> calculateRange()); LinearLayout.LayoutParams cp = new LinearLayout.LayoutParams(-1, dp(50)); cp.topMargin = dp(8); root.addView(calc, cp);\n        LinearLayout c = card(); LinearLayout.LayoutParams p = new LinearLayout.LayoutParams(-1, -2); p.topMargin = dp(8); root.addView(c, p);''','''        LinearLayout c = card(); LinearLayout.LayoutParams p = new LinearLayout.LayoutParams(-1, -2); p.topMargin = dp(10); root.addView(c, p);''',1)

s=s.replace('''        monthTitle.setText(displayedMonth.getYear() + "年" + displayedMonth.getMonthValue() + "月");''','''        monthTitle.setText(displayedMonth.getYear() + "年" + displayedMonth.getMonthValue() + "月\\n点击选择月份");''',1)
s=s.replace('''        DateTimeFormatter f = DateTimeFormatter.ofPattern("M月d日"); weekTitle.setText(displayedWeekStart.format(f) + " - " + weekEnd.format(f));''','''        DateTimeFormatter f = DateTimeFormatter.ofPattern("M月d日"); weekTitle.setText(displayedWeekStart.format(f) + " - " + weekEnd.format(f) + "\\n点击选择星期");''',1)

old_picker='''    private void showDatePicker(boolean startPicker){LocalDate initial=startPicker?rangeStart:rangeEnd,today=LocalDate.now(),ws=getWorkStartDate();if(ws!=null&&initial.isBefore(ws))initial=ws;DatePickerDialog d=new DatePickerDialog(this,(v,y,m,day)->{LocalDate s=LocalDate.of(y,m+1,day);if(s.isAfter(today))s=today;if(ws!=null&&s.isBefore(ws))s=ws;if(startPicker)rangeStart=s;else rangeEnd=s;updateRangeButtons();},initial.getYear(),initial.getMonthValue()-1,initial.getDayOfMonth());d.getDatePicker().setMaxDate(System.currentTimeMillis());if(ws!=null)d.getDatePicker().setMinDate(ws.atStartOfDay(java.time.ZoneId.systemDefault()).toInstant().toEpochMilli());d.show();}\n'''
new_picker='''    private void chooseWorkWeek(){LocalDate initial=displayedWeekStart,today=LocalDate.now(),ws=getWorkStartDate();DatePickerDialog d=new DatePickerDialog(this,(v,y,m,day)->{LocalDate picked=LocalDate.of(y,m+1,day);displayedWeekStart=mondayOf(picked);refreshWeek();},initial.getYear(),initial.getMonthValue()-1,initial.getDayOfMonth());d.getDatePicker().setMaxDate(System.currentTimeMillis());if(ws!=null)d.getDatePicker().setMinDate(ws.atStartOfDay(java.time.ZoneId.systemDefault()).toInstant().toEpochMilli());d.show();}\n    private void chooseWorkMonth(){LocalDate ws=getWorkStartDate();int minYear=ws==null?Math.max(2000,displayedMonth.getYear()-20):ws.getYear(),maxYear=YearMonth.now().getYear();LinearLayout box=horizontal();box.setPadding(dp(24),dp(12),dp(24),dp(4));box.setGravity(Gravity.CENTER);NumberPicker yp=new NumberPicker(this);yp.setMinValue(minYear);yp.setMaxValue(maxYear);yp.setValue(Math.max(minYear,Math.min(maxYear,displayedMonth.getYear())));box.addView(yp,new LinearLayout.LayoutParams(0,-2,1f));NumberPicker mp=new NumberPicker(this);mp.setMinValue(1);mp.setMaxValue(12);mp.setDisplayedValues(new String[]{"1月","2月","3月","4月","5月","6月","7月","8月","9月","10月","11月","12月"});mp.setValue(displayedMonth.getMonthValue());box.addView(mp,new LinearLayout.LayoutParams(0,-2,1f));AlertDialog dialog=new AlertDialog.Builder(this).setTitle("选择月份").setView(box).setNegativeButton("取消",null).setPositiveButton("确定",null).create();dialog.setOnShowListener(x->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{YearMonth picked=YearMonth.of(yp.getValue(),mp.getValue()),now=YearMonth.now(),first=ws==null?null:YearMonth.from(ws);if(picked.isAfter(now)){Toast.makeText(this,"不能选择未来月份",Toast.LENGTH_SHORT).show();return;}if(first!=null&&picked.isBefore(first)){Toast.makeText(this,"不能早于工作开始月份",Toast.LENGTH_SHORT).show();return;}displayedMonth=picked;refreshMonth();dialog.dismiss();}));dialog.show();}\n    private void showDatePicker(boolean startPicker){LocalDate initial=startPicker?rangeStart:rangeEnd,today=LocalDate.now(),ws=getWorkStartDate();if(ws!=null&&initial.isBefore(ws))initial=ws;DatePickerDialog d=new DatePickerDialog(this,(v,y,m,day)->{LocalDate s=LocalDate.of(y,m+1,day);if(s.isAfter(today))s=today;if(ws!=null&&s.isBefore(ws))s=ws;if(startPicker){rangeStart=s;if(rangeEnd.isBefore(rangeStart))rangeEnd=rangeStart;}else{rangeEnd=s;if(rangeStart.isAfter(rangeEnd))rangeStart=rangeEnd;}updateRangeButtons();calculateRange();},initial.getYear(),initial.getMonthValue()-1,initial.getDayOfMonth());d.getDatePicker().setMaxDate(System.currentTimeMillis());if(ws!=null)d.getDatePicker().setMinDate(ws.atStartOfDay(java.time.ZoneId.systemDefault()).toInstant().toEpochMilli());d.show();}\n'''
if old_picker not in s: raise SystemExit('date picker anchor not found')
s=s.replace(old_picker,new_picker,1)

s=s.replace('''    private void updateRangeButtons(){DateTimeFormatter f=DateTimeFormatter.ofPattern("yyyy-MM-dd");rangeStartButton.setText(rangeStart.format(f));rangeEndButton.setText(rangeEnd.format(f));}''','''    private void updateRangeButtons(){DateTimeFormatter f=DateTimeFormatter.ofPattern("yyyy-MM-dd");rangeStartButton.setText("开始\\n"+rangeStart.format(f));rangeEndButton.setText("结束\\n"+rangeEnd.format(f));}''',1)

p.write_text(s)
