from pathlib import Path
p=Path('app/src/main/java/com/example/workhours/WagePanel.java')
s=p.read_text()

s=s.replace('''    private Button selectedDateButton;\n    private TextView daySummary;\n''','''    private Button selectedDateButton;\n    private Button rangeStartButton;\n    private Button rangeEndButton;\n    private TextView daySummary;\n    private LinearLayout dayDetails;\n''',1)
s=s.replace('''    private LocalDate selectedDate;\n''','''    private LocalDate selectedDate;\n    private LocalDate rangeStartDate;\n    private LocalDate rangeEndDate;\n''',1)
s=s.replace('''        selectedDate = today;\n        buildUi();''','''        selectedDate = today;\n        rangeStartDate = mondayOf(today);\n        rangeEndDate = today;\n        buildUi();''',1)

s=s.replace('''        weekTitle = text("", 17, true);\n        weekTitle.setGravity(Gravity.CENTER);\n        weekNav.addView(weekTitle, new LinearLayout.LayoutParams(0, -2, 1f));''','''        weekTitle = text("", 17, true);\n        weekTitle.setGravity(Gravity.CENTER);\n        weekTitle.setPadding(dp(8), dp(12), dp(8), dp(12));\n        weekTitle.setOnClickListener(v -> chooseWeek());\n        weekNav.addView(weekTitle, new LinearLayout.LayoutParams(0, -2, 1f));''',1)

old='''        TextView daySection = text("按日期查看工资", 19, true);\n        daySection.setPadding(0, dp(18), 0, dp(8));\n        dayContent.addView(daySection);\n        selectedDateButton = button("");\n        selectedDateButton.setOnClickListener(v -> chooseDate());\n        dayContent.addView(selectedDateButton, new LinearLayout.LayoutParams(-1, dp(50)));\n        LinearLayout dayCard = card();\n        LinearLayout.LayoutParams dayCardParams = new LinearLayout.LayoutParams(-1, -2);\n        dayCardParams.topMargin = dp(10);\n        dayContent.addView(dayCard, dayCardParams);\n        daySummary = text("", 16, true);\n        dayCard.addView(daySummary);\n        TextView dayHint = text("扣工资请回到工时统计后点击对应日期修改。", 13, false);\n        dayHint.setPadding(0, dp(10), 0, 0);\n        dayCard.addView(dayHint);\n'''
new='''        TextView daySection = text("按日期范围查看工资", 19, true);\n        daySection.setPadding(0, dp(18), 0, dp(8));\n        dayContent.addView(daySection);\n        LinearLayout rangeRow = horizontal();\n        rangeRow.setGravity(Gravity.CENTER_VERTICAL);\n        dayContent.addView(rangeRow);\n        rangeStartButton = button("");\n        rangeStartButton.setOnClickListener(v -> chooseRangeDate(true));\n        rangeRow.addView(rangeStartButton, new LinearLayout.LayoutParams(0, dp(50), 1f));\n        TextView rangeTo = text(" 至 ", 15, true);\n        rangeTo.setGravity(Gravity.CENTER);\n        rangeRow.addView(rangeTo, new LinearLayout.LayoutParams(dp(42), dp(50)));\n        rangeEndButton = button("");\n        rangeEndButton.setOnClickListener(v -> chooseRangeDate(false));\n        rangeRow.addView(rangeEndButton, new LinearLayout.LayoutParams(0, dp(50), 1f));\n        LinearLayout dayCard = card();\n        LinearLayout.LayoutParams dayCardParams = new LinearLayout.LayoutParams(-1, -2);\n        dayCardParams.topMargin = dp(10);\n        dayContent.addView(dayCard, dayCardParams);\n        daySummary = text("", 16, true);\n        dayCard.addView(daySummary);\n        dayDetails = vertical();\n        dayCard.addView(dayDetails);\n        TextView dayHint = text("扣工资请回到工时统计后点击对应日期修改。", 13, false);\n        dayHint.setPadding(0, dp(10), 0, 0);\n        dayCard.addView(dayHint);\n'''
if old not in s: raise SystemExit('day UI anchor not found')
s=s.replace(old,new,1)

# Replace chooseDate with week/range picker helpers, preserving old method name unused only if needed.
start=s.index('    private void chooseDate() {')
end=s.index('    private void saveDeduction()', start)
replacement='''    private void chooseWeek() {\n        LocalDate initial = displayedWeekStart;\n        DatePickerDialog dialog = new DatePickerDialog(host, (view, y, m, d) -> {\n            LocalDate picked = LocalDate.of(y, m + 1, d);\n            displayedWeekStart = mondayOf(picked);\n            refreshWeek();\n        }, initial.getYear(), initial.getMonthValue() - 1, initial.getDayOfMonth());\n        dialog.getDatePicker().setMaxDate(System.currentTimeMillis());\n        LocalDate ws = getWorkStartDate();\n        if (ws != null) dialog.getDatePicker().setMinDate(ws.atStartOfDay(java.time.ZoneId.systemDefault()).toInstant().toEpochMilli());\n        dialog.show();\n    }\n\n    private void chooseRangeDate(boolean startDate) {\n        LocalDate initial = startDate ? rangeStartDate : rangeEndDate;\n        DatePickerDialog dialog = new DatePickerDialog(host, (view, y, m, d) -> {\n            LocalDate picked = LocalDate.of(y, m + 1, d);\n            if (startDate) {\n                rangeStartDate = picked;\n                if (rangeEndDate.isBefore(rangeStartDate)) rangeEndDate = rangeStartDate;\n            } else {\n                rangeEndDate = picked;\n                if (rangeStartDate.isAfter(rangeEndDate)) rangeStartDate = rangeEndDate;\n            }\n            refreshDay();\n        }, initial.getYear(), initial.getMonthValue() - 1, initial.getDayOfMonth());\n        dialog.getDatePicker().setMaxDate(System.currentTimeMillis());\n        LocalDate ws = getWorkStartDate();\n        if (ws != null) dialog.getDatePicker().setMinDate(ws.atStartOfDay(java.time.ZoneId.systemDefault()).toInstant().toEpochMilli());\n        dialog.show();\n    }\n\n'''
s=s[:start]+replacement+s[end:]

# Replace refreshDay body up to refreshWeek.
start=s.index('    private void refreshDay() {')
end=s.index('    private void refreshWeek() {', start)
replacement='''    private void refreshDay() {\n        if (rangeStartButton == null || rangeEndButton == null || daySummary == null || dayDetails == null) return;\n        LocalDate today = LocalDate.now();\n        LocalDate ws = getWorkStartDate();\n        if (rangeEndDate.isAfter(today)) rangeEndDate = today;\n        if (ws != null && rangeStartDate.isBefore(ws)) rangeStartDate = ws;\n        if (rangeStartDate.isAfter(rangeEndDate)) rangeEndDate = rangeStartDate;\n\n        DateTimeFormatter buttonFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");\n        rangeStartButton.setText("开始\\n" + rangeStartDate.format(buttonFormat));\n        rangeEndButton.setText("结束\\n" + rangeEndDate.format(buttonFormat));\n        dayDetails.removeAllViews();\n\n        float hours = 0f, wage = 0f, deduction = 0f;\n        int workDays = 0, deductionDays = 0;\n        DateTimeFormatter rowFormat = DateTimeFormatter.ofPattern("M月d日 E", Locale.CHINA);\n        for (LocalDate d = rangeStartDate; !d.isAfter(rangeEndDate); d = d.plusDays(1)) {\n            float h = getHours(d);\n            float before = getWageBeforeDeduction(d);\n            float after = getWageForDate(d);\n            hours += h;\n            wage += after;\n            if (h > 0) workDays++;\n            if (isDeducted(d)) { deduction += before; deductionDays++; }\n            if (h > 0 || before > 0 || isDeducted(d) || isLeave(d) || isBankHoliday(d) || isManualRest(d)) {\n                TextView row = text(d.format(rowFormat) + " ｜ " + getDayStatus(d)\n                        + " ｜ " + formatHours(h) + " ｜ " + money(after)\n                        + (isDeducted(d) ? " ｜ 已扣工资" : ""), 13, isDeducted(d));\n                row.setPadding(0, dp(4), 0, dp(4));\n                dayDetails.addView(row);\n            }\n        }\n        long days = java.time.temporal.ChronoUnit.DAYS.between(rangeStartDate, rangeEndDate) + 1;\n        daySummary.setText("日期范围：" + rangeStartDate.format(buttonFormat) + " 至 " + rangeEndDate.format(buttonFormat)\n                + "（" + days + "天）"\n                + "\\n总工时：" + formatHours(hours) + " ｜ 工作：" + workDays + "天"\n                + "\\n总工资：" + money(wage) + " ｜ 已扣：" + money(deduction)\n                + " ｜ 扣工资：" + deductionDays + "天");\n    }\n\n'''
s=s[:start]+replacement+s[end:]

# refreshAll normalize range around work start.
s=s.replace('''        if (ws != null && selectedDate.isBefore(ws)) selectedDate = ws;\n        refreshWeek();''','''        if (ws != null && selectedDate.isBefore(ws)) selectedDate = ws;\n        if (ws != null && rangeStartDate.isBefore(ws)) rangeStartDate = ws;\n        if (rangeEndDate.isBefore(rangeStartDate)) rangeEndDate = rangeStartDate;\n        refreshWeek();''',1)

# Add visible hint on week title.
s=s.replace('''        weekTitle.setText(displayedWeekStart.format(f) + " - " + end.format(f));''','''        weekTitle.setText(displayedWeekStart.format(f) + " - " + end.format(f) + "\\n点击选择星期");''',1)

p.write_text(s)
